version: '3.8'

services:
  la-huerta-app_develop:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: la-huerta-server
    container_name: la-huerta_develop
    restart: always
    ports:
      - ${PORT}:${PORT}

  db:
    image: postgres:15.4
    container_name: huertaDB
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json